import { exec } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { rimraf } from 'rimraf';
import { Registry } from 'shadcn/schema';

import { SOURCE_CODE_GITHUB_URL } from '../config/site';
import { USER } from '../config/user';
import { registry } from '../registry/index';


async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map((file) => `registry/${file.path}`);
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/${item.files[0].path}`
      : '';

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `registry/${typeof file === 'string' ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === 'string'
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : 'null'
    },
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  // Write style index.
  rimraf.sync(path.join(process.cwd(), 'registry/__index__.tsx'));
  await fs.writeFile(path.join(process.cwd(), 'registry/__index__.tsx'), index);
}

async function buildRegistryJsonFile() {
  // 1. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `registry/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), `registry.json`));
  await fs.writeFile(
    path.join(process.cwd(), `registry.json`),
    JSON.stringify(fixedRegistry, null, 2)
  );

  // 3. Copy the registry.json to the public/r directory.
  await fs.cp(
    path.join(process.cwd(), 'registry.json'),
    path.join(process.cwd(), './public/r/registry.json'),
    { recursive: true }
  );

  // 3. Copy the registry.json to the public/r directory.
  await fs.cp(
    path.join(process.cwd(), 'registry.json'),
    path.join(process.cwd(), './public/registry.json'),
    { recursive: true }
  );
}

type RegistryItem = Registry['items'][number];

type FileEntry = string | { path: string; type?: string; target?: string };

async function readRegistryFilesContents(item: RegistryItem): Promise<string> {
  if (!item.files?.length) return '';

  const paths = item.files
    .map((f: FileEntry) => (typeof f === 'string' ? f : f?.path))
    .filter(Boolean)
    .sort() as string[];

  // Read all files in parallel
  const contents = await Promise.all(
    paths.map(async (filePath) => {
      try {
        const content = await fs.readFile(
          path.join(process.cwd(), 'registry', filePath),
          'utf8'
        );
        return `--- file: ${filePath} ---\n${content.endsWith('\n') ? content : content + '\n'}`;
      } catch {
        return null; // Skip missing files
      }
    })
  );

  // Join non-null contents with blank lines between them
  return contents.filter(Boolean).join('\n');
}

function getComponentExamples() {
  const examplesByComponent = new Map<string, string[]>();

  registry.items
    .filter((item) => item.type === 'registry:example')
    .forEach((example) => {
      example.registryDependencies?.forEach((dep) => {
        const componentName = dep.split('/').pop();
        if (componentName) {
          if (!examplesByComponent.has(componentName)) {
            examplesByComponent.set(componentName, []);
          }
          examplesByComponent.get(componentName)!.push(example.name);
        }
      });
    });

  return examplesByComponent;
}


async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const process = exec(`pnpm shadcn:build`);

    process.on('exit', (code) => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.log('��️ Building registry/__index__.tsx...');
  await buildRegistryIndex();
  console.log('✅ Registry index built successfully');

  console.log('💅 Building registry.json...');
  await buildRegistryJsonFile();
  console.log('✅ Registry JSON file built successfully');

  console.log('🏗️ Building registry...');
  await buildRegistry();
  console.log('✅ Registry build completed');
} catch (error) {
  console.error('❌ Build failed with error:');
  console.error(error);
  if (error instanceof Error) {
    console.error('Error stack:', error.stack);
  }
  process.exit(1);
}
